### ISSUE TITLE
fatal error: pylon/PylonIncludes.h: No such file or direcytory

### ISSUE THREAD

**Issue by chrisburtner** [JasonNPitt/wormbotV3F#1]
Hello,
We are working with Ubuntu 18.04.6 LTS and following the documentation for V3. We have installed arduino and uploaded wormbot_firmware_ino.ino. After cloning the git and installing the software, we receive an error:

`src/controller.cpp:56:11: fatal error: pylon/PylonIncludes.h: No such file or directory
#include <pylon/PylonIncludes.h>
compliation terminated
makefile:30: recipe for target 'controller' failed
make: *** [controller] Error 1
head: cannot open 'etc/systemd/system/multi-user.target.wants/rw-local.service -> /
etc/systemd/system/rc-local.service.`

During install, we chose 'U' for the UVC camera (mokose USB camera) and 12 for the full size wormbot.

Can you please help us solve the error with pylon? Thank you!

Chris
